name: Build docker box

on: 
  workflow_call:  
    inputs:
      dockerVersion:
        required: true
        type: string
      debianVersion:
        required: true
        type: string
    outputs:
      ManifestFile:
        description: "The resulted packer manifest file"
        value: ${{ jobs.buildDocker.outputs.ManifestFile }}

jobs:
  buildDocker:
    runs-on: self-hosted-1
    outputs:
      ManifestFile: ${{ steps.build.outputs.manifestfile}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Cleaning previous artifacts
        run: make clean
      - name: Build the vagrant box
        id: build
        run: make build CURRENT_DOCKER_VERSION=${{ inputs.dockerVersion }} CURRENT_DEBIAN_VERSION=${{ inputs.debianVersion }}

  testCreatedBox:
    runs-on: self-hosted-1
    needs: buildDocker
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Testing the vagrant box
        run: make test MANIFESTFILE=${{ needs.buildDocker.outputs.ManifestFile }}