name: Check if new Docker box must be built
on: 
  workflow_call:  
    outputs:
      Verdict:
        description: "True: a new Docker box must be built"
        value: ${{ jobs.versions.outputs.verdict }}

jobs:
  versions:
    runs-on: ubuntu-20.04
    outputs:
      verdict: ${{ steps.versions.outputs.verdict == 'true' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get version list
        id: versions
        run: make checkifbuild
