name: Check if new docker version exist

on: 
  workflow_call:  
    outputs:
      newexist:
        description: "True: exist new docker version. False: does not exist new docker version"
        value: ${{ jobs.check_if_new_docker_exist.outputs.verdict == 'true' }}

jobs:
  check_if_new_docker_exist:
    runs-on: ubuntu-20.04
    outputs:
      verdict: ${{ steps.version.outputs.verdict }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Check if new docker veresion exist
        id: version
        run: make version && "::set-output name=verdict::true" || echo "::set-output name=verdict::false"
