name: Create docker box version automaticaly

on:
  workflow_dispatch:
  schedule:
    - cron: '* 3 * * *'
env:
  VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

jobs:
  CheckIfBuild:
    uses: ./.github/workflows/CheckIfBuild-reusable.yml

  GetVersions:
    needs: [CheckIfBuild]
    if: needs.CheckIfBuild.outputs.Verdict
    uses: ./.github/workflows/GetVersions-reusable.yml

  ConcatStrings:
    needs: [GetVersions]
    runs-on: self-hosted-2
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Create list to pass into BuildDocker job
        id: version
        run: echo ::set-output name=version::$( echo ${{ needs.GetVersions.outputs.dockerVersion }} | jq -ncR '[inputs]')


  BuildAndUploadDocker:
    needs: [GetVersions, ConcatStrings]
    uses:  ./.github/workflows/Build-Box-reusable.yml
    with:
      dockerVersions: ${{ needs.ConcatStrings.outputs.version }}
    secrets: inherit

  Clean:
    needs: [GetVersions, ConcatStrings, BuildAndUploadDocker]
    uses: ./.github/workflows/Clean-reusable.yml
