name: Check if new docker version exist

on: 
  workflow_call:  
    outputs:
      verdict:
        description: "True: exist new docker version. False: does not exist new docker version"
        value: ${{ jobs.check_if_new_docker_exist.outputs.verdict }}
      debianVersion:
        description: "The debian version to build the box"
        value: ${{ jobs.check_if_new_docker_exist.outputs.debianversion }}
      dockerVersion: 
        description: "The docker version to build the box"
        value: ${{ jobs.check_if_new_docker_exist.outputs.dockerversion }}

jobs:
  check_if_new_docker_exist:
    runs-on: ubuntu-20.04
    outputs:
      verdict: ${{ steps.version.outputs.verdict }}
      debianversion: ${{ steps.version.outputs.debianversion }}
      dockerversion: ${{ steps.version.outputs.dockerversion }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Check if new docker veresion exist
        id: version
        run: make version && "::set-output name=verdict::true" || echo "::set-output name=verdict::false"
