name: Clean
on: 
  workflow_call: 

jobs:
  Uploader:
    runs-on: self-hosted-1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Done
        run: make clean