name: Create docker box version manually

on:
  workflow_dispatch:
    inputs:
      Version:
        required: true
        type: string

env:
  VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

jobs:
  GetVersions:
    uses: ./.github/workflows/GetVersions-reusable.yml

  #Uploader:
  #  needs: GetVersions
  #  uses: ./.github/workflows/uploader-reusable.yml

  ConcatStrings:
    runs-on: self-hosted-2
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Create list to pass into BuildDocker job
        id: version
        run: echo ::set-output name=version::$( echo ${{ inputs.Version }} | jq -ncR '[inputs]')


  BuildAndUploadDocker:
    needs: [GetVersions, ConcatStrings]
    uses:  ./.github/workflows/Build-Box-reusable.yml
    with:
      dockerVersions: ${{ needs.ConcatStrings.outputs.version }}
    secrets: inherit

  Clean:
    needs: [GetVersions, ConcatStrings, BuildAndUploadDocker]
    uses: ./.github/workflows/Clean-reusable.yml
