name: Get Docker, Debian and box Versions

on: 
  workflow_call:  
    outputs:
      debianVersion:
        description: "The debian version to build the box"
        value: ${{ jobs.versions.outputs.debianversion }}
      dockerVersion: 
        description: "The docker version to build the box"
        value: ${{ jobs.versions.outputs.dockerversion }}
      dockerreleases:
        description: "All docker released versions"
        value: ${{ jobs.versions.outputs.dockerreleases }}
      currentboxversion:
        description: "The current docker box version"
        value: ${{ jobs.versions.outputs.dockerreleases }}

jobs:
  versions:
    runs-on: ubuntu-20.04
    outputs:
      debianversion: ${{ steps.versions.outputs.debianversion }}
      dockerversion: ${{ steps.versions.outputs.dockerversion }}
      dockerreleases: ${{ steps.versions.outputs.alldockerreleases }}
      currenetboxversion: ${{ steps.versions.outputs.boxversion }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Get version list
        id: versions
        run: make versions
