name: Rebuild all Docker boxes
on:
  workflow_dispatch:

env:
  VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

jobs:
  GetVersions:
    uses: ./.github/workflows/GetVersions-reusable.yml

  BuildAndUploadDocker:
    needs: [GetVersions]
    uses:  ./.github/workflows/Build-Box-reusable.yml
    with:
      dockerVersions: ${{ needs.GetVersions.outputs.currentboxversions }}
    secrets: inherit

  Clean:
    needs: [GetVersions, BuildAndUploadDocker]
    uses: ./.github/workflows/Clean-reusable.yml
