name: Test Docker box

on: 
  workflow_call:
    inputs:
      dockerVersions:
        required: true
        type: string

jobs:
  Test:
    strategy:
      max-parallel: 3
      matrix:
        provider: [virtualbox,vmware_desktop,parallels]
        version: ${{ fromJSON(inputs.dockerVersions) }}
        include:
          - provider: virtualbox
            runner: self-hosted-1
          - provider: vmware_desktop
            runner: self-hosted-2
          - provider: parallels
            runner: self-hosted-3

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build Docker box
        run: make test CURRENT_DOCKER_VERSION=${{ matrix.version }} PROVIDER=${{ matrix.provider }}
