name: Test created box
on: 
  workflow_call:  
    inputs:
      ManifestFile:
        required: true
        type: string

jobs:
  testbox:
    runs-on: self-hosted-1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Testing the vagrant box
        run: make test MANIFESTFILE=${{ inputs.ManifestFile }}