name: Upgrade Docker boxes
on:
  schedule:
    - cron: '0 3 1 * *'
  workflow_dispatch:

env:
  VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

jobs:
  GetAllDockerReleasesVersions:
    uses: ./.github/workflows/get-docker-releases-versions.yml
  
  UpgradingBoxes:
    runs-on: self-hosted-1
    needs: GetAllDockerReleasesVersions
    strategy:
      max-parallel: 1
      matrix:
        version: ${{ fromJSON(needs.GetAllDockerReleasesVersions.outputs.versions) }}
    steps:
      - name: Deleting box version ${{ matrix.version }}
        run: make deleteVersion VERSION=${{ matrix.version }}
      - name: Re-build docker box ${{ matrix.version }}
        run: make build CURRENT_DOCKER_VERSION=${{ matrix.version }}
      - name: Test docker box ${{ matrix.version }}
        run: make test CURRENT_DOCKER_VERSION=${{ matrix.version }}
      - name: Upload docker box to vagrant cloud ${{ matrix.version }}
        run: make upload CURRENT_DOCKER_VERSION=${{ matrix.version }}
      - name: Clean docker box ${{ matrix.version }}
        run: make clean CURRENT_DOCKER_VERSION=${{ matrix.version }}