name: Upgrade Docker boxes
on:
  schedule:
    - cron: '0 3 1 * *'
  workflow_dispatch:

env:
  VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

jobs:
  GetAllDockerReleasesVersions:
    uses: ./.github/workflows/get-docker-releases-versions.yml
  
  UpgradingBoxes:
    runs-on: self-hosted-1
    needs: GetAllDockerReleasesVersions
    strategy:
      max-parallel: 1
      matrix:
        version: ${{ fromJSON(needs.GetAllDockerReleasesVersions.outputs.versions) }}
        provider: [virtualbox,vmware,parallels]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Re-build docker box ${{ matrix.version }} on ${{ matrix.provider }} provider
        run: make build CURRENT_DOCKER_VERSION=${{ matrix.version }} PROVIDER=${{ matrix.provider }}
      - name: Deleting box version ${{ matrix.version }} on ${{ matrix.provider }} provider
        run: make deleteVersion VERSION=${{ matrix.version }} PROVIDER=${{ matrix.provider }}
      - name: Upload docker box to vagrant cloud ${{ matrix.version }} on ${{ matrix.provider }} provider
        run: make upload CURRENT_DOCKER_VERSION=${{ matrix.version }} PROVIDER=${{ matrix.provider }}
      - name: Clean docker box ${{ matrix.version }} on ${{ matrix.provider }} provider
        run: make clean CURRENT_DOCKER_VERSION=${{ matrix.version }} PROVIDER=${{ matrix.provider }}