name: Upload the created box to Vagrant Cloud
on: 
  workflow_call:
    inputs:
      boxFile:
        required: true
        type: string
      dockerVersion:
        required: true
        type: string
      debianVersion:
        required: true
        type: string
    secrets:
      VAGRANT_CLOUD_TOKEN:
        required: true

env:
  VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

jobs:
  uploadBox:
    runs-on: self-hosted-1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Upload
        id: version
        run: make upload BOXFILE=${{ inputs.boxFile }} CURRENT_DOCKER_VERSION=${{ inputs.dockerVersion }} CURRENT_DEBIAN_VERSION=${{ inputs.debianVersion }}